sudo: required
dist: trusty
language: java
jdk:
#  - openjdk6
#  - openjdk7
  - oraclejdk7
  - oraclejdk8
addons:
  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
  hostname: localhost
